name: your_upi
description: A UPI QR code scanner and generator app.
publish_to: 'none' # private project

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  qr_code_scanner: ^0.7.0
  qr_flutter: ^4.0.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  path: ^1.8.2
  share_plus: ^6.3.0
  clipboard: ^0.1.3
  provider: ^6.0.5
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
